config/routes.rb
Rails.application.routes.draw do
  resources :students
  root 'students#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    def index
        @students = student.all
    end
  
    def new
        @student = student.new
    end

    def create
        student = student.new(tweet_params)
        if student.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end
    
      private
      def student_params
        params.require(:student).permit(:name, :profile, :mentor, :grade)
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geekkobe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/index.html.erb
<h1>GeekKobe</h1>
<h3>投稿一覧</h3>
<%= link_to "新規投稿へ", new_student_path %>
<div class="students-container">
<% @students.each do |t| %>
    <%= t.name %>
    <%= t.profile %>
    <%= t.mentor %>
    <%= t.grade %>
    <%= t.created_at %>
    </div>
  <% end %>
</div>

app/views/students/new.html.erb
<h1>GeekKobe</h1>
<h3>新規投稿</h3>
<%= form_for @student do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :profile %>
    <%= f.text_field :profile, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :mentor %>
    <%= f.text_field :profile, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :grade %>
    <%= f.select :shop_name, 
    [["１年", "1年"], 
    ["2年", "2年"], 
    ["3年", "3年"],
    ["4年", "4年"],
    ["院1年", "院1年"],
    ["院2年", "院2年"],
    ["院3年", "院3年"]], include_blank: "選択して下さい" %>
  </div>
  <%= f.submit "投稿する" %>
<% end %>

<%= link_to "一覧に戻る", students_path %>